package co.gov.minenergia.jbpm.orfeo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrfeoDocumentList implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrfeoDocumentList() {
    }




}