package co.gov.minenergia.jbpm.orfeo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Lista de Documentos")
public class OrfeoDocumentList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Documentos")
	private java.util.List<co.gov.minenergia.jbpm.orfeo.OrfeoDocument> documentos;

	public OrfeoDocumentList() {
	}

	public java.util.List<co.gov.minenergia.jbpm.orfeo.OrfeoDocument> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(
			java.util.List<co.gov.minenergia.jbpm.orfeo.OrfeoDocument> documentos) {
		this.documentos = documentos;
	}

	public OrfeoDocumentList(
			java.util.List<co.gov.minenergia.jbpm.orfeo.OrfeoDocument> documentos) {
		this.documentos = documentos;
	}
    
    @Override
	public String toString() {
		
		Gson gson = new GsonBuilder().setPrettyPrinting().create();
		return gson.toJson(this);
	}
}