package co.gov.minenergia.jbpm.data;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Configuración de Notificaciones")
public class NotificationConfig implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Notificaciones")
	private java.util.List<co.gov.minenergia.jbpm.data.EmailNotification> notificaciones;

	public NotificationConfig() {
	}

	public java.util.List<co.gov.minenergia.jbpm.data.EmailNotification> getNotificaciones() {
		return this.notificaciones;
	}

	public void setNotificaciones(
			java.util.List<co.gov.minenergia.jbpm.data.EmailNotification> notificaciones) {
		this.notificaciones = notificaciones;
	}

	public NotificationConfig(
			java.util.List<co.gov.minenergia.jbpm.data.EmailNotification> notificaciones) {
		this.notificaciones = notificaciones;
	}

}