package co.gov.minenergia.jbpm.data;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Recurso")
public class Recurso implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Radicado")
	private java.lang.String numeroRadicado;
	@org.kie.api.definition.type.Label(value = "Respuesta Recurso")
	private co.gov.minenergia.jbpm.data.Document respuesta;
	@org.kie.api.definition.type.Label(value = "Respuesta Modifica Decisión?")
	private java.lang.Boolean respuestaModificaDecisionFlag;
	@org.kie.api.definition.type.Label(value = "Etapa Proceso")
	private java.lang.String etapa;

	public Recurso() {
	}

	public java.lang.String getNumeroRadicado() {
		return this.numeroRadicado;
	}

	public void setNumeroRadicado(java.lang.String numeroRadicado) {
		this.numeroRadicado = numeroRadicado;
	}

	public co.gov.minenergia.jbpm.data.Document getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(co.gov.minenergia.jbpm.data.Document respuesta) {
		this.respuesta = respuesta;
	}

	public java.lang.Boolean getRespuestaModificaDecisionFlag() {
		return this.respuestaModificaDecisionFlag;
	}

	public void setRespuestaModificaDecisionFlag(
			java.lang.Boolean respuestaModificaDecisionFlag) {
		this.respuestaModificaDecisionFlag = respuestaModificaDecisionFlag;
	}

	public java.lang.String getEtapa() {
		return this.etapa;
	}

	public void setEtapa(java.lang.String etapa) {
		this.etapa = etapa;
	}

	public Recurso(java.lang.String numeroRadicado,
			co.gov.minenergia.jbpm.data.Document respuesta,
			java.lang.Boolean respuestaModificaDecisionFlag,
			java.lang.String etapa) {
		this.numeroRadicado = numeroRadicado;
		this.respuesta = respuesta;
		this.respuestaModificaDecisionFlag = respuestaModificaDecisionFlag;
		this.etapa = etapa;
	}
	
	@Override
	public String toString() {
		
		Gson gson = new GsonBuilder().setPrettyPrinting().create();
		return gson.toJson(this);
	}

}